
[build-system]
requires = ["hatchling","hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "ai-powered-customer-engagement-platform"
version = "0.0.1"
authors = [
  { name="Aman Kapoor" },
  { name="Vidushi Jain" },
]
# maintainers = [
#   { name="Raghav B. Venkataramaiyer",
#     email="bvraghav@gmail.com" },
# ]
description = "WhatsApp-first AI real-estate lead qualification and advisor dashboard"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    # See: https://pypi.org/classifiers/
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: POSIX",
    "Programming Language :: Unix Shell",
]
dependencies = ["click"]

[project.urls]
Homepage = "https://github.com/vidushi2536/AI-Powered-Customer-Engagement-Platform-"
Issues = "https://github.com/vidushi2536/AI-Powered-Customer-Engagement-Platform-/issues"

# Adapted from https://stackoverflow.com/a/50156706
[tool.pytest.ini_options]
pythonpath = [
  "code"
]
# THE END -------------------------------------------
